  
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (1, 'Bello', 1,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (2, 'Caldas', 1,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (3, 'Copacabana', 1,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (4, 'Envigado', 1,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (5, 'Guarne', 1,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (6, 'Itagui', 1,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (7, 'La Ceja', 1,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (8, 'La Estrella', 1,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (9, 'La Tablaza', 1,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (10, 'Marinilla', 1,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (11, 'Medellín', 1,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (12, 'Rionegro', 1,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (13, 'Sabaneta', 1,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (14, 'San Antonio de Prado', 1,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (15, 'San Cristóbal', 1,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (16, 'Caucasia', 1,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (17, 'Barranquilla', 2,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (18, 'Malambo', 2,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (19, 'Puerto Colombia', 2,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (20, 'Soledad', 2,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (21, 'Arjona', 3,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (22, 'Bayunca', 3,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (23, 'Carmen de Bolívar', 3,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (24, 'Cartagena', 3,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (25, 'Turbaco', 3,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (26, 'Arcabuco', 4,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (27, 'Belencito', 4,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (28, 'Chiquinquirá', 4,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (29, 'Combita', 4,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (30, 'Cucaita', 4,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (31, 'Duitama', 4,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (32, 'Mongui', 4,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (33, 'Nobsa', 4,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (34, 'Paipa', 4,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (35, 'Puerto Boyacá', 4,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (36, 'Ráquira', 4,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (37, 'Samaca', 4,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (38, 'Santa Rosa de Viterbo', 4,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (39, 'Sogamoso', 4,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (40, 'Sutamerchán', 4,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (41, 'Tibasosa', 4,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (42, 'Tinjaca', 4,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (43, 'Tunja', 4,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (44, 'Ventaquemada', 4,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (45, 'Villa de Leiva', 4,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (46, 'La Dorada', 5,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (47, 'Manizales', 5,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (48, 'Villamaria', 5,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (49, 'Caloto', 6,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (50, 'Ortigal', 6,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (51, 'Piendamo', 6,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (52, 'Popayán', 6,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (53, 'Puerto Tejada', 6,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (54, 'Santander Quilichao', 6,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (55, 'Tunia', 6,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (56, 'Villarica', 6,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (57, 'Valledupar', 7,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (58, 'Cerete', 8,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (59, 'Montería', 8,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (60, 'Planeta Rica', 8,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (61, 'Alban', 9,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (62, 'Bogotá', 9,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (63, 'Bojaca', 9,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (64, 'Bosa', 9,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (65, 'Briceño', 9,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (66, 'Cajicá', 9,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (67, 'Chía', 9,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (68, 'Chinauta', 9,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (69, 'Choconta', 9,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (70, 'Cota', 9,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (71, 'El Muña', 9,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (72, 'El Rosal', 9,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (73, 'Engativá', 9,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (74, 'Facatativa', 9,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (75, 'Fontibón', 9,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (76, 'Funza', 9,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (77, 'Fusagasuga', 9,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (78, 'Gachancipá', 9,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (79, 'Girardot', 9,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (80, 'Guaduas', 9,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (81, 'Guayavetal', 9,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (82, 'La Calera', 9,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (83, 'La Caro', 9,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (84, 'Madrid', 9,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (85, 'Mosquera', 9,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (86, 'Nemocón', 9,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (87, 'Puente Piedra', 9,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (88, 'Puente Quetame', 9,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (89, 'Puerto Bogotá', 9,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (90, 'Puerto Salgar', 9,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (91, 'Quetame', 9,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (92, 'Sasaima', 9,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (93, 'Sesquile', 9,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (94, 'Sibaté', 9,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (95, 'Silvania', 9,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (96, 'Simijaca', 9,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (97, 'Soacha', 9,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (98, 'Sopo', 9,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (99, 'Suba', 9,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (100, 'Subachoque', 9,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (101, 'Susa', 9,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (102, 'Tabio', 9,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (103, 'Tenjo', 9,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (104, 'Tocancipa', 9,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (105, 'Ubaté', 9,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (106, 'Usaquén', 9,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (107, 'Usme', 9,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (108, 'Villapinzón', 9,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (109, 'Villeta', 9,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (110, 'Zipaquirá', 9,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (111, 'Maicao', 10,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (112, 'Riohacha', 10,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (113, 'Aipe', 11,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (114, 'Neiva', 11,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (115, 'Cienaga', 12,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (116, 'Gaira', 12,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (117, 'Rodadero', 12,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (118, 'Santa Marta', 12,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (119, 'Taganga', 12,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (120, 'Villavicencio', 13,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (121, 'Ipiales', 14,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (122, 'Pasto', 14,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (123, 'Cúcuta', 15,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (124, 'El Zulia', 15,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (125, 'La Parada', 15,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (126, 'Los Patios', 15,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (127, 'Villa del Rosario', 15,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (128, 'Armenia', 16,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (129, 'Calarcá', 16,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (130, 'Circasia', 16,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (131, 'La Tebaida', 16,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (132, 'Montenegro', 16,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (133, 'Quimbaya', 16,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (134, 'Dosquebradas', 17,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (135, 'Pereira', 17,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (136, 'Aratoca', 18,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (137, 'Barbosa', 18,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (138, 'Bucaramanga', 18,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (139, 'Floridablanca', 18,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (140, 'Girón', 18,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (141, 'Lebrija', 18,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (142, 'Oiba', 18,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (143, 'Piedecuesta', 18,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (144, 'Pinchote', 18,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (145, 'San Gil', 18,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (146, 'Socorro', 18,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (147, 'Sincelejo', 19,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (148, 'Armero', 20,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (149, 'Buenos Aires', 20,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (150, 'Castilla', 20,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (151, 'Espinal', 20,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (152, 'Flandes', 20,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (153, 'Guamo', 20,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (154, 'Honda', 20,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (155, 'Ibagué', 20,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (156, 'Mariquita', 20,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (157, 'Melgar', 20,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (158, 'Natagaima', 20,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (159, 'Payande', 20,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (160, 'Purificación', 20,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (161, 'Saldaña', 20,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (162, 'Tolemaida', 20,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (163, 'Amaime', 21,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (164, 'Andalucía', 21,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (165, 'Buenaventura', 21,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (166, 'Buga', 21,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (167, 'Buga La Grande', 21,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (168, 'Caicedonia', 21,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (169, 'Cali', 21,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (170, 'Candelaria', 21,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (171, 'Cartago', 21,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (172, 'Cavasa', 21,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (173, 'Costa Rica', 21,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (174, 'Dagua', 21,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (175, 'El Carmelo', 21,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (176, 'El Cerrito', 21,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (177, 'El Placer', 21,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (178, 'Florida', 21,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (179, 'Ginebra', 21,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (180, 'Guacarí', 21,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (181, 'Jamundi', 21,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (182, 'La Paila', 21,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (183, 'La Unión', 21,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (184, 'La Victoria', 21,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (185, 'Loboguerrero', 21,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (186, 'Palmira', 21,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (187, 'Pradera', 21,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (188, 'Roldanillo', 21,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (189, 'Rozo', 21,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (190, 'San Pedro', 21,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (191, 'Sevilla', 21,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (192, 'Sonso', 21,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (193, 'Tulúa', 21,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (194, 'Vijes', 21,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (195, 'Villa Gorgona', 21,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (196, 'Yotoco', 21,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (197, 'Yumbo', 21,'ADMIN',SYSDATE); 
INSERT INTO ciudad (id_ciudad, nombre_ciudad, id_departamento,USUARIO_CREACION,fecha_creacion) VALUES  (198, 'Zarzal', 21,'ADMIN',SYSDATE); 


